### ISSUE TITLE
SPARTA build cmake failure

### ISSUE THREAD

**Issue by OrenGitHub** [facebook/SPARTA#9]
Hi,
I followed installation steps and got the following error (Ubuntu 18.04):
```
$ mkdir build-cmake
$ cd build-cmake
$ cmake ..
$ cmake --build . 
make: *** No targets specified and no makefile found.  Stop.
```
and indeed there is no `Makefile` inside `SPARTA/build-cmake`.
What am I doing wrong ? Thanks !

**Comment by yuxuanchen1997** [comment]
Can you try to replace the third command to
```
cmake .. -G "Unix Makefiles"
```
?

**Comment by yuxuanchen1997** [comment]
Sorry. You might want to have the latest fixes included in order to build the tests. #10 is the fix.

**Comment by OrenGitHub** [comment]
tried `cmake .. -G "Unix Makefiles"` but it also failed, should I try something else?

**Comment by yuxuanchen1997** [comment]
Do you mind pasting here what `cmake .. -G "Unix Makefiles"` prints? Did it succeed?

**Comment by OrenGitHub** [comment]
turns out it was just a boost compatibility thing ...
although the `README` says `ubuntu 16.04` and later should be fine with:
```
sudo apt-get install libboost-all-dev
```
When I used:
```
sudo ./get_boost.sh
```
Everything worked fine
